# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TIS_new_order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_New_Order(object):
    def setupUi(self, Dialog_New_Order):
        Dialog_New_Order.setObjectName("Dialog_New_Order")
        Dialog_New_Order.resize(968, 566)
        self.groupBox = QtWidgets.QGroupBox(Dialog_New_Order)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 831, 91))
        self.groupBox.setObjectName("groupBox")
        self.comb_supplier = QtWidgets.QComboBox(self.groupBox)
        self.comb_supplier.setEnabled(True)
        self.comb_supplier.setGeometry(QtCore.QRect(70, 20, 81, 22))
        self.comb_supplier.setEditable(True)
        self.comb_supplier.setObjectName("comb_supplier")
        self.lb_supplier_new_order = QtWidgets.QLabel(self.groupBox)
        self.lb_supplier_new_order.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_supplier_new_order.setFont(font)
        self.lb_supplier_new_order.setObjectName("lb_supplier_new_order")
        self.lb_style_new_order = QtWidgets.QLabel(self.groupBox)
        self.lb_style_new_order.setGeometry(QtCore.QRect(170, 20, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_style_new_order.setFont(font)
        self.lb_style_new_order.setObjectName("lb_style_new_order")
        self.comb_style = QtWidgets.QComboBox(self.groupBox)
        self.comb_style.setEnabled(True)
        self.comb_style.setGeometry(QtCore.QRect(200, 20, 101, 22))
        self.comb_style.setEditable(True)
        self.comb_style.setObjectName("comb_style")
        self.lb_recap_8 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_8.setGeometry(QtCore.QRect(320, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_recap_8.setFont(font)
        self.lb_recap_8.setObjectName("lb_recap_8")
        self.dateE_orderdate = QtWidgets.QDateEdit(self.groupBox)
        self.dateE_orderdate.setGeometry(QtCore.QRect(390, 20, 81, 20))
        self.dateE_orderdate.setObjectName("dateE_orderdate")
        self.lb_recap_4 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_4.setGeometry(QtCore.QRect(220, 50, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_recap_4.setFont(font)
        self.lb_recap_4.setObjectName("lb_recap_4")
        self.lin_abmno = QtWidgets.QLineEdit(self.groupBox)
        self.lin_abmno.setGeometry(QtCore.QRect(270, 50, 121, 20))
        self.lin_abmno.setObjectName("lin_abmno")
        self.lb_recap_5 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_5.setGeometry(QtCore.QRect(630, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_recap_5.setFont(font)
        self.lb_recap_5.setObjectName("lb_recap_5")
        self.lin_ctmno = QtWidgets.QLineEdit(self.groupBox)
        self.lin_ctmno.setGeometry(QtCore.QRect(710, 20, 111, 20))
        self.lin_ctmno.setObjectName("lin_ctmno")
        self.lb_recap_7 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_7.setGeometry(QtCore.QRect(470, 40, 117, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_recap_7.setFont(font)
        self.lb_recap_7.setObjectName("lb_recap_7")
        self.comb_shipment = QtWidgets.QComboBox(self.groupBox)
        self.comb_shipment.setGeometry(QtCore.QRect(530, 50, 291, 20))
        self.comb_shipment.setObjectName("comb_shipment")
        self.lb_recap_6 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_6.setGeometry(QtCore.QRect(10, 50, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_recap_6.setFont(font)
        self.lb_recap_6.setObjectName("lb_recap_6")
        self.lin_tisno = QtWidgets.QLineEdit(self.groupBox)
        self.lin_tisno.setGeometry(QtCore.QRect(60, 50, 111, 20))
        self.lin_tisno.setObjectName("lin_tisno")
        self.lb_supplier_new_order_2 = QtWidgets.QLabel(self.groupBox)
        self.lb_supplier_new_order_2.setGeometry(QtCore.QRect(500, 20, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_supplier_new_order_2.setFont(font)
        self.lb_supplier_new_order_2.setObjectName("lb_supplier_new_order_2")
        self.comb_client = QtWidgets.QComboBox(self.groupBox)
        self.comb_client.setEnabled(True)
        self.comb_client.setGeometry(QtCore.QRect(540, 20, 81, 22))
        self.comb_client.setEditable(True)
        self.comb_client.setObjectName("comb_client")
        self.groupB_size_1 = QtWidgets.QGroupBox(Dialog_New_Order)
        self.groupB_size_1.setEnabled(True)
        self.groupB_size_1.setGeometry(QtCore.QRect(10, 100, 951, 201))
        self.groupB_size_1.setObjectName("groupB_size_1")
        self.tableW_size_1 = QtWidgets.QTableWidget(self.groupB_size_1)
        self.tableW_size_1.setGeometry(QtCore.QRect(10, 20, 931, 171))
        self.tableW_size_1.setObjectName("tableW_size_1")
        self.tableW_size_1.setColumnCount(0)
        self.tableW_size_1.setRowCount(0)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_New_Order)
        self.buttonBox.setGeometry(QtCore.QRect(850, 10, 111, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.groupB_size_2 = QtWidgets.QGroupBox(Dialog_New_Order)
        self.groupB_size_2.setEnabled(False)
        self.groupB_size_2.setGeometry(QtCore.QRect(10, 310, 951, 121))
        self.groupB_size_2.setObjectName("groupB_size_2")
        self.tableW_size_2 = QtWidgets.QTableWidget(self.groupB_size_2)
        self.tableW_size_2.setGeometry(QtCore.QRect(10, 20, 931, 91))
        self.tableW_size_2.setObjectName("tableW_size_2")
        self.tableW_size_2.setColumnCount(0)
        self.tableW_size_2.setRowCount(0)
        self.groupB_size_3 = QtWidgets.QGroupBox(Dialog_New_Order)
        self.groupB_size_3.setEnabled(False)
        self.groupB_size_3.setGeometry(QtCore.QRect(10, 440, 951, 121))
        self.groupB_size_3.setObjectName("groupB_size_3")
        self.tableW_size_3 = QtWidgets.QTableWidget(self.groupB_size_3)
        self.tableW_size_3.setGeometry(QtCore.QRect(10, 20, 931, 91))
        self.tableW_size_3.setObjectName("tableW_size_3")
        self.tableW_size_3.setColumnCount(0)
        self.tableW_size_3.setRowCount(0)
        self.lb_recap_9 = QtWidgets.QLabel(Dialog_New_Order)
        self.lb_recap_9.setGeometry(QtCore.QRect(850, 80, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_recap_9.setFont(font)
        self.lb_recap_9.setObjectName("lb_recap_9")
        self.lin_total = QtWidgets.QLineEdit(Dialog_New_Order)
        self.lin_total.setGeometry(QtCore.QRect(890, 80, 61, 20))
        self.lin_total.setReadOnly(True)
        self.lin_total.setObjectName("lin_total")

        self.retranslateUi(Dialog_New_Order)
        self.buttonBox.accepted.connect(Dialog_New_Order.accept)
        self.buttonBox.rejected.connect(Dialog_New_Order.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_New_Order)

    def retranslateUi(self, Dialog_New_Order):
        _translate = QtCore.QCoreApplication.translate
        Dialog_New_Order.setWindowTitle(_translate("Dialog_New_Order", "New Order"))
        self.groupBox.setTitle(_translate("Dialog_New_Order", "OrderRecap"))
        self.lb_supplier_new_order.setText(_translate("Dialog_New_Order", "Supplier"))
        self.lb_style_new_order.setText(_translate("Dialog_New_Order", "Style"))
        self.lb_recap_8.setText(_translate("Dialog_New_Order", "OrderDate"))
        self.lb_recap_4.setText(_translate("Dialog_New_Order", "ABM No."))
        self.lb_recap_5.setText(_translate("Dialog_New_Order", "Client PO No."))
        self.lb_recap_7.setText(_translate("Dialog_New_Order", "Shipment"))
        self.lb_recap_6.setText(_translate("Dialog_New_Order", "TIS No."))
        self.lb_supplier_new_order_2.setText(_translate("Dialog_New_Order", "Client"))
        self.groupB_size_1.setTitle(_translate("Dialog_New_Order", "Size Breakup Regular"))
        self.groupB_size_2.setTitle(_translate("Dialog_New_Order", "Size Breakup Stout"))
        self.groupB_size_3.setTitle(_translate("Dialog_New_Order", "Size Breakup Long"))
        self.lb_recap_9.setText(_translate("Dialog_New_Order", "Total"))

