# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TIS_edit_order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editDialog_Order(object):
    def setupUi(self, editDialog_Order):
        editDialog_Order.setObjectName("editDialog_Order")
        editDialog_Order.resize(874, 566)
        self.groupBox = QtWidgets.QGroupBox(editDialog_Order)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 611, 91))
        self.groupBox.setObjectName("groupBox")
        self.lb_recap_1 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_1.setGeometry(QtCore.QRect(10, 10, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_1.setFont(font)
        self.lb_recap_1.setObjectName("lb_recap_1")
        self.lb_recap_2 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_2.setGeometry(QtCore.QRect(20, 40, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_2.setFont(font)
        self.lb_recap_2.setObjectName("lb_recap_2")
        self.groupBox_2 = QtWidgets.QGroupBox(editDialog_Order)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 851, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lb_recap_8 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_recap_8.setGeometry(QtCore.QRect(360, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_8.setFont(font)
        self.lb_recap_8.setObjectName("lb_recap_8")
        self.dateE_orderdate = QtWidgets.QDateEdit(self.groupBox_2)
        self.dateE_orderdate.setGeometry(QtCore.QRect(450, 20, 111, 20))
        self.dateE_orderdate.setObjectName("dateE_orderdate")
        self.lb_recap_7 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_recap_7.setGeometry(QtCore.QRect(20, 40, 117, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_7.setFont(font)
        self.lb_recap_7.setObjectName("lb_recap_7")
        self.lb_recap_4 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_recap_4.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_4.setFont(font)
        self.lb_recap_4.setObjectName("lb_recap_4")
        self.lin_abmno = QtWidgets.QLineEdit(self.groupBox_2)
        self.lin_abmno.setGeometry(QtCore.QRect(100, 20, 151, 20))
        self.lin_abmno.setObjectName("lin_abmno")
        self.comb_shipment = QtWidgets.QComboBox(self.groupBox_2)
        self.comb_shipment.setGeometry(QtCore.QRect(100, 50, 291, 20))
        self.comb_shipment.setObjectName("comb_shipment")
        self.groupB_size_1 = QtWidgets.QGroupBox(editDialog_Order)
        self.groupB_size_1.setEnabled(True)
        self.groupB_size_1.setGeometry(QtCore.QRect(10, 200, 851, 101))
        self.groupB_size_1.setObjectName("groupB_size_1")
        self.tableW_size_1 = QtWidgets.QTableWidget(self.groupB_size_1)
        self.tableW_size_1.setGeometry(QtCore.QRect(60, 20, 761, 78))
        self.tableW_size_1.setObjectName("tableW_size_1")
        self.tableW_size_1.setColumnCount(0)
        self.tableW_size_1.setRowCount(0)
        self.toolBtn_plus_1 = QtWidgets.QToolButton(self.groupB_size_1)
        self.toolBtn_plus_1.setGeometry(QtCore.QRect(820, 68, 31, 31))
        self.toolBtn_plus_1.setWhatsThis("")
        self.toolBtn_plus_1.setObjectName("toolBtn_plus_1")
        self.label = QtWidgets.QLabel(self.groupB_size_1)
        self.label.setGeometry(QtCore.QRect(16, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupB_size_1)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupB_size_1)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(editDialog_Order)
        self.buttonBox.setGeometry(QtCore.QRect(640, 40, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.groupB_size_2 = QtWidgets.QGroupBox(editDialog_Order)
        self.groupB_size_2.setEnabled(False)
        self.groupB_size_2.setGeometry(QtCore.QRect(10, 320, 851, 101))
        self.groupB_size_2.setObjectName("groupB_size_2")
        self.tableW_size_2 = QtWidgets.QTableWidget(self.groupB_size_2)
        self.tableW_size_2.setGeometry(QtCore.QRect(60, 20, 761, 78))
        self.tableW_size_2.setObjectName("tableW_size_2")
        self.tableW_size_2.setColumnCount(0)
        self.tableW_size_2.setRowCount(0)
        self.toolBtn_plus_2 = QtWidgets.QToolButton(self.groupB_size_2)
        self.toolBtn_plus_2.setGeometry(QtCore.QRect(820, 68, 31, 31))
        self.toolBtn_plus_2.setWhatsThis("")
        self.toolBtn_plus_2.setObjectName("toolBtn_plus_2")
        self.label_6 = QtWidgets.QLabel(self.groupB_size_2)
        self.label_6.setGeometry(QtCore.QRect(0, 50, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.groupB_size_2)
        self.label_5.setGeometry(QtCore.QRect(16, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupB_size_2)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.tableW_size_2.raise_()
        self.toolBtn_plus_1.raise_()
        self.toolBtn_plus_2.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.groupB_size_3 = QtWidgets.QGroupBox(editDialog_Order)
        self.groupB_size_3.setEnabled(False)
        self.groupB_size_3.setGeometry(QtCore.QRect(10, 440, 851, 101))
        self.groupB_size_3.setObjectName("groupB_size_3")
        self.tableW_size_3 = QtWidgets.QTableWidget(self.groupB_size_3)
        self.tableW_size_3.setGeometry(QtCore.QRect(60, 20, 761, 78))
        self.tableW_size_3.setObjectName("tableW_size_3")
        self.tableW_size_3.setColumnCount(0)
        self.tableW_size_3.setRowCount(0)
        self.toolBtn_plus_3 = QtWidgets.QToolButton(self.groupB_size_3)
        self.toolBtn_plus_3.setGeometry(QtCore.QRect(820, 68, 31, 31))
        self.toolBtn_plus_3.setWhatsThis("")
        self.toolBtn_plus_3.setObjectName("toolBtn_plus_3")
        self.label_9 = QtWidgets.QLabel(self.groupB_size_3)
        self.label_9.setGeometry(QtCore.QRect(0, 50, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.groupB_size_3)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupB_size_3)
        self.label_8.setGeometry(QtCore.QRect(16, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.groupB_size_1.raise_()
        self.buttonBox.raise_()
        self.groupB_size_2.raise_()
        self.groupB_size_3.raise_()

        self.retranslateUi(editDialog_Order)
        self.buttonBox.accepted.connect(editDialog_Order.accept)
        self.buttonBox.rejected.connect(editDialog_Order.reject)
        QtCore.QMetaObject.connectSlotsByName(editDialog_Order)

    def retranslateUi(self, editDialog_Order):
        _translate = QtCore.QCoreApplication.translate
        editDialog_Order.setWindowTitle(_translate("editDialog_Order", "Edit Order"))
        self.groupBox.setTitle(_translate("editDialog_Order", "OrderRecap"))
        self.lb_recap_1.setText(_translate("editDialog_Order", " Recap"))
        self.lb_recap_2.setText(_translate("editDialog_Order", "Recap"))
        self.groupBox_2.setTitle(_translate("editDialog_Order", "Schedule"))
        self.lb_recap_8.setText(_translate("editDialog_Order", "OrderDate"))
        self.lb_recap_7.setText(_translate("editDialog_Order", "Shipment"))
        self.lb_recap_4.setText(_translate("editDialog_Order", "ABM No."))
        self.groupB_size_1.setTitle(_translate("editDialog_Order", "Size Breakup Regular"))
        self.toolBtn_plus_1.setToolTip(_translate("editDialog_Order", "Add quantity left"))
        self.toolBtn_plus_1.setText(_translate("editDialog_Order", "Ok"))
        self.label.setText(_translate("editDialog_Order", "Size"))
        self.label_2.setToolTip(_translate("editDialog_Order", "Current quantity"))
        self.label_2.setText(_translate("editDialog_Order", "Current"))
        self.label_3.setToolTip(_translate("editDialog_Order", "example: +5 or -5"))
        self.label_3.setText(_translate("editDialog_Order", "+/-"))
        self.groupB_size_2.setTitle(_translate("editDialog_Order", "Size Breakup Stout"))
        self.toolBtn_plus_2.setToolTip(_translate("editDialog_Order", "Add quantity left"))
        self.toolBtn_plus_2.setText(_translate("editDialog_Order", "Ok"))
        self.label_6.setToolTip(_translate("editDialog_Order", "Current quantity"))
        self.label_6.setText(_translate("editDialog_Order", "Current"))
        self.label_5.setText(_translate("editDialog_Order", "Size"))
        self.label_4.setToolTip(_translate("editDialog_Order", "example: +5 or -5"))
        self.label_4.setText(_translate("editDialog_Order", "+/-"))
        self.groupB_size_3.setTitle(_translate("editDialog_Order", "Size Breakup Long"))
        self.toolBtn_plus_3.setToolTip(_translate("editDialog_Order", "Add quantity left"))
        self.toolBtn_plus_3.setText(_translate("editDialog_Order", "Ok"))
        self.label_9.setToolTip(_translate("editDialog_Order", "Current quantity"))
        self.label_9.setText(_translate("editDialog_Order", "Current"))
        self.label_7.setToolTip(_translate("editDialog_Order", "example: +5 or -5"))
        self.label_7.setText(_translate("editDialog_Order", "+/-"))
        self.label_8.setText(_translate("editDialog_Order", "Size"))

