# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TIS_edit_order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editDialog_Order(object):
    def setupUi(self, editDialog_Order):
        editDialog_Order.setObjectName("editDialog_Order")
        editDialog_Order.resize(774, 554)
        self.buttonBox = QtWidgets.QDialogButtonBox(editDialog_Order)
        self.buttonBox.setGeometry(QtCore.QRect(600, 500, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.comb_shipment = QtWidgets.QComboBox(editDialog_Order)
        self.comb_shipment.setGeometry(QtCore.QRect(110, 180, 291, 20))
        self.comb_shipment.setObjectName("comb_shipment")
        self.groupBox = QtWidgets.QGroupBox(editDialog_Order)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 751, 121))
        self.groupBox.setObjectName("groupBox")
        self.lb_recap_1 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_1.setGeometry(QtCore.QRect(10, 10, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_1.setFont(font)
        self.lb_recap_1.setObjectName("lb_recap_1")
        self.lb_recap_2 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_2.setGeometry(QtCore.QRect(20, 40, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_2.setFont(font)
        self.lb_recap_2.setObjectName("lb_recap_2")
        self.lb_recap_3 = QtWidgets.QLabel(self.groupBox)
        self.lb_recap_3.setGeometry(QtCore.QRect(20, 70, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_3.setFont(font)
        self.lb_recap_3.setObjectName("lb_recap_3")
        self.groupBox_2 = QtWidgets.QGroupBox(editDialog_Order)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 751, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lb_recap_8 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_recap_8.setGeometry(QtCore.QRect(360, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_8.setFont(font)
        self.lb_recap_8.setObjectName("lb_recap_8")
        self.dateE_orderdate = QtWidgets.QDateEdit(self.groupBox_2)
        self.dateE_orderdate.setGeometry(QtCore.QRect(450, 20, 111, 20))
        self.dateE_orderdate.setObjectName("dateE_orderdate")
        self.lb_recap_7 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_recap_7.setGeometry(QtCore.QRect(20, 40, 117, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_7.setFont(font)
        self.lb_recap_7.setObjectName("lb_recap_7")
        self.lb_recap_4 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_recap_4.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_recap_4.setFont(font)
        self.lb_recap_4.setObjectName("lb_recap_4")
        self.lin_abmno = QtWidgets.QLineEdit(self.groupBox_2)
        self.lin_abmno.setGeometry(QtCore.QRect(100, 20, 151, 20))
        self.lin_abmno.setObjectName("lin_abmno")
        self.groupBox_3 = QtWidgets.QGroupBox(editDialog_Order)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 230, 751, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 10, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.buttonBox.raise_()
        self.comb_shipment.raise_()
        self.groupBox_3.raise_()

        self.retranslateUi(editDialog_Order)
        self.buttonBox.accepted.connect(editDialog_Order.accept)
        self.buttonBox.rejected.connect(editDialog_Order.reject)
        QtCore.QMetaObject.connectSlotsByName(editDialog_Order)

    def retranslateUi(self, editDialog_Order):
        _translate = QtCore.QCoreApplication.translate
        editDialog_Order.setWindowTitle(_translate("editDialog_Order", "Edit Order"))
        self.groupBox.setTitle(_translate("editDialog_Order", "OrderRecap"))
        self.lb_recap_1.setText(_translate("editDialog_Order", " Recap"))
        self.lb_recap_2.setText(_translate("editDialog_Order", "Recap"))
        self.lb_recap_3.setText(_translate("editDialog_Order", "Recap"))
        self.groupBox_2.setTitle(_translate("editDialog_Order", "Schedule"))
        self.lb_recap_8.setText(_translate("editDialog_Order", "OrderDate"))
        self.lb_recap_7.setText(_translate("editDialog_Order", "Shipment"))
        self.lb_recap_4.setText(_translate("editDialog_Order", "ABM No."))
        self.groupBox_3.setTitle(_translate("editDialog_Order", "Size Breakup Regular"))

