# Generated by Django 2.0.2 on 2018-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etd', models.DateTimeField()),
                ('eta', models.DateTimeField()),
                ('instore', models.DateTimeField()),
                ('instore_abm', models.DateTimeField()),
                ('total_quantity', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cartons', models.IntegerField()),
                ('mode', models.TextField(choices=[('S', 'Seafreight'), ('F', 'Airfreight'), ('C', 'Courier')], default='S', max_length=1)),
                ('etd_port', models.TextField(choices=[('GUANGZHOU', 'Guangzhou'), ('NINGBO', 'Ningbo'), ('SHANGHAI', 'Shanghai'), ('QINGDAO', 'Qingdao'), ('XINGANG', 'Xingang'), ('BEIJING', 'Beijing'), ('OTHER', 'other')], default='GUANGZHOU')),
                ('eta_port', models.TextField(choices=[('BRISBANE', 'Brisbane'), ('SYDNEY', 'Sydney'), ('MELBOURNE', 'Melbourne'), ('OTHER', 'Other')], default='BRISBANE')),
                ('container', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Shipments',
                'ordering': ('etd_port', 'etd'),
                'verbose_name': 'Shipment',
            },
        ),
    ]
