# Generated by Django 2.0.2 on 2018-03-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='cartons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='eta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='etd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='instore',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='instore_abm',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volume',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
