# Generated by Django 2.0.2 on 2018-03-28 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20180314_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='etd',
            field=models.DateField(default=datetime.date(2018, 3, 28)),
        ),
    ]
