# Generated by Django 2.0.2 on 2018-03-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20180328_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='instore_abm',
            field=models.DateField(null=True),
        ),
    ]
