# Generated by Django 2.0.2 on 2018-04-03 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20180328_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='supplier',
            field=models.TextField(default='AUWIN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='etd',
            field=models.DateField(default=datetime.date(2018, 4, 3)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='mode',
            field=models.TextField(choices=[('Sea', 'Seafreight'), ('Air', 'Airfreight'), ('Courier', 'Courier')], default='Sea', max_length=1),
        ),
    ]
