# Generated by Django 2.0.2 on 2018-04-27 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_auto_20180420_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='etd',
            field=models.DateField(default=datetime.date(2018, 4, 27)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='mode',
            field=models.TextField(choices=[('Sea', 'Seafreight'), ('Air', 'Airfreight'), ('Courier', 'Courier')], default='Sea', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
