# Generated by Django 2.0.2 on 2018-04-30 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20180427_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='etd',
            field=models.DateField(default=datetime.date(2018, 4, 30)),
        ),
    ]
