# Generated by Django 2.0.2 on 2018-03-14 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricTrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_solid', models.TextField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Fabric Trims in Order',
                'verbose_name': 'Fabric Trim in Order',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tis_no', models.CharField(max_length=15)),
                ('internal_no', models.CharField(max_length=11)),
                ('ctm_no', models.CharField(max_length=50)),
                ('client', models.TextField(max_length=50)),
                ('supplier', models.TextField(max_length=50)),
                ('colour', models.TextField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.Shipment')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ('tis_no', 'colour'),
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='SampleCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'PP Sample'), ('S', 'Shipping Sample'), ('F', 'Fabric Swatch'), ('T', 'Test Report'), ('I', 'Inspection'), ('D', 'Shipping Doc')], max_length=1)),
                ('status', models.CharField(choices=[('N', 'No Need'), ('Y', 'Need'), ('S', 'Sent'), ('R', 'Received'), ('A', 'Approved'), ('R', 'Rejected')], default='N', max_length=1)),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('ref', models.TextField(max_length=100)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FabricTrim')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'verbose_name_plural': 'Checkings',
                'ordering': ('check_date',),
                'verbose_name': 'Checking',
            },
        ),
        migrations.AddField(
            model_name='fabrictrim',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
