# Generated by Django 2.0.2 on 2018-04-12 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180328_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecheck',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.FabricTrim'),
        ),
        migrations.AlterField(
            model_name='samplecheck',
            name='ref',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplecheck',
            name='status',
            field=models.CharField(choices=[('N', 'No Need'), ('Y', 'Need'), ('S', 'Sent'), ('G', 'Received'), ('A', 'Approved'), ('R', 'Rejected')], default='N', max_length=1),
        ),
    ]
