# Generated by Django 2.0.2 on 2018-04-12 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180412_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecheck',
            name='check_date',
            field=models.DateField(default=datetime.date(2018, 4, 12)),
        ),
    ]
