# Generated by Django 2.0.2 on 2018-04-16 04:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180412_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='samplecheck',
            name='check_date',
            field=models.DateField(default=datetime.date(2018, 4, 16)),
        ),
    ]
