# Generated by Django 2.0.2 on 2018-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_no', models.TextField(max_length=50)),
                ('commodity', models.TextField(max_length=100)),
                ('fabric', models.TextField(max_length=100)),
                ('fabric_usage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantiy_per_carton', models.IntegerField()),
                ('volume_per_carton', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight_per_carton', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('style_no',),
                'verbose_name': 'Product',
            },
        ),
    ]
