# Generated by Django 2.0.2 on 2018-03-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiy_per_carton',
            new_name='quantity_per_carton',
        ),
    ]
