# Generated by Django 2.0.2 on 2018-03-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180328_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commodity',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_per_carton',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_per_carton',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_per_carton',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
