# Generated by Django 2.0.2 on 2018-04-16 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180416_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Fabric'),
        ),
    ]
