# Generated by Django 2.0.2 on 2018-04-24 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180416_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, to='products.Fabric'),
        ),
    ]
